version: "3.2"

services:
  hackney-shared-patches-and-areas-test:
    image: hackney-shared-patches-and-areas-test
    build:
      context: .
      dockerfile: Hackney.Shared.PatchesAndAreas.Tests/Dockerfile
      secrets:
        - LBHPACKAGESTOKEN

# see https://docs.docker.com/compose/how-tos/use-secrets/#build-secrets
# Combines with a "secrets" block in each service to expose it as a file in
# /run/secrets/, e.g. /run/secrets/LBHPACKAGESTOKEN
secrets:
  LBHPACKAGESTOKEN:
    environment: LBHPACKAGESTOKEN
